spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  output:
    ansi:
      enabled: ALWAYS

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
